### ISSUE TITLE
Feature: User can sign up for Deck Study

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#1]
## ⚙️ Feature

> ##### User can sign up for an account by providing a username and password. 

## 📐 Functionality

> ##### User can click Sign Up on the Navigation Bar to be provided with a form to enter their desired username and password. 

## 🖼️ Wireframes

> ##### Wireframe screenshots
![Screen Shot 2022-09-12 at 11 58 01 AM](https://user-images.githubusercontent.com/49361894/189734323-ce199ef7-61ed-4e74-a6bc-08bca0779071.png)
![Screen Shot 2022-09-12 at 11 58 25 AM](https://user-images.githubusercontent.com/49361894/189734326-9316c029-19a8-4608-8c3d-97756d8f8cdc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `index.js` to handle a user sign up request at /api/auth/sign-up
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create an Auth page component that will be rendered by App.jsx when user is null and hash is ' ' 
- [x] Update NavBar component to contain a Sign-Up Button with an anchor for 'sign-up'
- [x] Create an AuthForm component that will be a child of the Auth Page component
- [x] Implement functionality for handling username and password state change in AuthForm
- [x] Implement functionality for sending post request to the server on Auth Page
- [x] Test flow of application to ensure button clicks trigger correct hash change.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
