### ISSUE TITLE
Feature: User can study deck

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can study a deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User enters the study page by clicking the book icon of a desk. On the study page, they are presented with a randomly generated card from their deck. They will be presented with the question and can click Reveal Answer to update the card with the answer. They will be prompted to rate the difficulty of the card. Once they rate the difficulty, they will move onto the next card. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-22 at 5 42 04 PM](https://user-images.githubusercontent.com/49361894/191874417-7f060270-e6fd-4447-9a55-41884d1cd42f.png)
![Screen Shot 2022-09-22 at 5 42 23 PM](https://user-images.githubusercontent.com/49361894/191874421-9d5901d3-2a52-4fc9-85a1-fc8cf7872b9b.png)
![Screen Shot 2022-09-22 at 5 42 50 PM](https://user-images.githubusercontent.com/49361894/191874423-965948b2-87c6-4196-a33e-57905da414df.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update index.js to handle a POST Request for inserting a difficulty rating as well as an Update Request for updating a Difficulty Rating. 
- [x] Update index.js to handle a GET Request that responds with all cards of a specified deckId, ordered by difficulty (descending).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a Study Page Component
- [x] Update App.jsx to render this component with the appropriate props
- [x] Render two stacked cards (one for the question and one for the answer)
- [x] Implement CSS to flip the card
- [x] Implement a Ratings Prompt in which the user can rate the difficulty
- [x] Implement Component methods to update the ratings on the server
- [x] Implement a deck sort which loads more difficult questions at the front of the deck and easier questions in the back.
- [x] Test the component

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
