### ISSUE TITLE
Feature: User can Sign In to account

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#2]
## ⚙️ Feature

> ##### A user will be able to sign in to their account.

## 📐 Functionality

> ##### User will be able to click the Sign In button and be prompted to enter in log in credentials. The server
will verify this login and grant an access token to the user. The user's page will then reset and display the deck
list page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s)
![Screen Shot 2022-09-12 at 12 44 24 PM](https://user-images.githubusercontent.com/49361894/189742039-6b65b242-5def-413e-a5f7-cc9abd772068.png)
![Screen Shot 2022-09-12 at 12 44 45 PM](https://user-images.githubusercontent.com/49361894/189742042-794f5b45-1342-4430-91bd-7b3d79a1bb02.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update index.js from hard coded userId value to one provided from the req. 
- [x] Create a server route for handling user Sign In. Server should respond with the user object and a digitally signed token.
- [x] Instantiate an instance of authorization-middleware above server routes which require user authorization

### ⚡ Client Tasks

- [x] Update Auth Form Component for sign-in action
- [x] Create a handleSignIn method on the app.jsx component which will update the user and token after receiving the response from the server
- [x] Ensure the handleSignIn method stores the token in the browser's local storage. Update componentDidMount to grab this token from local storage. 
- [x] Update request headers with the token for all routes that require user authorization.
- [x] Test with multiple user accounts. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
