### ISSUE TITLE
Design Update: UI-Welcome-Screen

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#28]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create hero banner that follows UI theme
- [x] Implement feature description section 1: Create/Manage Cards
- [x] Implement feature description section 2: Study Cards
- [x] Implement a Get Started button that directs user to the Sign Up page
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
