### ISSUE TITLE
Feature: User can browse course decks

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#3]
## ⚙️ Feature

> ##### User can browse their course decks.

## 📐 Functionality

> ##### After user logs in, they are redirected to the decks list page. This page will display a list of the user's decks (if any) in the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s)
![Screen Shot 2022-09-12 at 12 47 52 PM](https://user-images.githubusercontent.com/49361894/189742560-ae17e91e-69ae-4c71-a6e6-758f892cdcaa.png)
![Screen Shot 2022-09-12 at 12 48 04 PM](https://user-images.githubusercontent.com/49361894/189742568-473dac84-7920-4f14-87f0-b3938089951d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Start PG Web Server. Ensure Database is properly configured.

### ☁️ Server Tasks

- [x] Update index.js with a GET request route to obtain all decks in the decks table.
- [x] Ensure proper error handling when sending response to client

### ⚡ Client Tasks

- [x] Test Client GET Requests with HTTPie
- [x] Update Deck Page Component to retrieve all decks from database.
- [x] Create Deck List Component which will display the decks in the Deck Page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
