### ISSUE TITLE
Bug: Empty Deck does not show placeholder text first card is added. 

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#30]
## 🐛 Bug

When adding a card to an empty Deck, there is no placeholder text when returning to the edit screen. 

#### Desired Behavior

> ##### The edit screen should display the newly added question/answer data

#### Actual Behavior

> ##### The edit screen shows black text area boxes for the question and answer.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Fix the bug preventing the placeholder text from displaying when adding the first card to the deck. 
- [x] Update the add card functionality to display the newly added card to the user
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
