### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#36]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user clicks the delete icon in a deck, they will be prompted with a delete confirmation modal. The user will be required to write the name of the deck to confirm their delete. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to handle delete route for deleting a user deck. This will delete all cards linked to this deckId. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Implement delete modal in Decks Component. Use will need to type out deck name in order to confirm delete. 
- [ ] Implement delete method in Deck Class Component. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
