### ISSUE TITLE
Feature: User can add a course deck

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#4]
## ⚙️ Feature

> ##### User can add a course deck. 

## 📐 Functionality

> ##### User clicks the add course deck option to render an "Add Deck" modal. The user can then enter the name of the deck and click the Add button. The deck list page will render with the newly added deck. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) 
![Screen Shot 2022-09-12 at 12 51 07 PM](https://user-images.githubusercontent.com/49361894/189743315-51705804-400b-45b7-bcc1-f0d4c0df947a.png)
![Screen Shot 2022-09-12 at 12 51 26 PM](https://user-images.githubusercontent.com/49361894/189743437-969eb7a5-6bb0-4893-852c-a76267c1a9b1.png)
![Screen Shot 2022-09-12 at 12 51 45 PM](https://user-images.githubusercontent.com/49361894/189743318-a79d1d7e-c878-4da4-8908-d80730d8e12f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to properly configure the tables and columns of the database
- [x] Update `data.sql` to import test user into our database users tables.
- [x] Run Pgweb server to ensure that GUI displays proper configuration of database. 

### ☁️ Server Tasks

- [x] Initialize index.js to include necessary requirements
- [x] Create post route in index.js that will insert the user request into our decks table

### ⚡ Client Tasks

- [x] Test client requests to post decks into our database.
- [x] Create App component  

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
