### ISSUE TITLE
Feature: User can edit cards in a deck

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#5]
## ⚙️ Feature

> ##### User will be able to edit the question and/or answer of a flash card in a deck.

## 📐 Functionality

> ##### The user clicks the edit icon on a course deck to enter the card list view. There is a nav menu to switch between edit and browse views. By default, the user enters the edit view. In the edit view, the user can click through the entire deck and manually edit the question and/or answer. After the changes have been made, the user can click the update button to update the flashcard in the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 1 07 20 PM](https://user-images.githubusercontent.com/49361894/189749184-e894500a-d13f-45a1-98d3-b768876412cc.png)
![Screen Shot 2022-09-12 at 1 07 36 PM](https://user-images.githubusercontent.com/49361894/189749188-1d602858-a422-4798-8f5c-979729d9aa69.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to insert deck/course data to initialize database.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle a PUT Request for a specified cardID. 
- [x] Test this request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Edit Cards component to display all cards in the current deck.
- [x] Implement a card layout with input fields for the question and answer. 
- [x] Implement form submission which will send a fetch request with a PUT method to the server. 
- [x] Overwrite the previous value in the cards array with the newly updated value. 
- [x] Test throughly to ensure proper functionality. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
