### ISSUE TITLE
Feature: User can add new card to deck

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#6]
## ⚙️ Feature

> ##### User can add a card to a deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the edit icon on a course deck, they are taken to the edit view of the deck. By default, the user will
be taken to the last card in the deck. There will be a plus button for the user to add a new card. Clicking this new button 
renders a New Card Form that the user can fill out. Once completed, the user can click the add button to add this card to the deck. The edit view will render once again with the newly added card. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 1 16 00 PM](https://user-images.githubusercontent.com/49361894/189750545-1b9a0485-9ba7-4631-949d-8285ebe283d8.png)
![Screen Shot 2022-09-12 at 1 16 09 PM](https://user-images.githubusercontent.com/49361894/189750547-e9303638-a189-4717-9a0c-a3f6a4dd2ba1.png)
![Screen Shot 2022-09-12 at 1 16 22 PM](https://user-images.githubusercontent.com/49361894/189750550-b6b7d88f-e15a-467e-8aa1-b0dd3eb04e3d.png)
![Screen Shot 2022-09-12 at 1 16 34 PM](https://user-images.githubusercontent.com/49361894/189750552-7695e790-272e-4d51-b350-aedbdafb965e.png)
![Screen Shot 2022-09-12 at 1 16 49 PM](https://user-images.githubusercontent.com/49361894/189750555-dc768263-3651-44df-81c2-dd57373735ca.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Review database configuration

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle a POST Request for adding a flash card for a given deck into the database.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

![image](https://user-images.githubusercontent.com/49361894/190238773-2c86b9d2-92b8-45b1-8881-3819cebf4df9.png)

- [x] Test post request with HTTPie
- [x] Create a component to input card field data (question, answer). 
- [x] Test component with database. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
