### ISSUE TITLE
Feature: User can browse cards in deck

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse their cards in a course deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the card list view, the user can click the browse nav tab to switch to browse view rather than edit. Here the user can click through the cards in the deck. When presented with the question, the user can click Reveal Answer to flip the card. When presented with the answer, the user can click Reveal Question to flip the card. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-09-12 at 1 20 31 PM](https://user-images.githubusercontent.com/49361894/189751312-f99f653c-4439-4c9c-8414-07f2da52c5a8.png)
![Screen Shot 2022-09-12 at 1 20 45 PM](https://user-images.githubusercontent.com/49361894/189751316-58f88f9c-9305-4720-9963-d843e3935aee.png)
![Screen Shot 2022-09-12 at 1 21 05 PM](https://user-images.githubusercontent.com/49361894/189751319-08027264-cf31-48cb-9cb0-2fde35895571.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to generate initial card data. 

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle a GET request for all the cards belonging to a deck
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Continue developing upon deck-cards component which will fetch these cards from out server
- [x] Create browse-cards component which will be used to browse the deck

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
