### ISSUE TITLE
Feature: User can delete a card from deck

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a card from their deck.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the edit view, when clicking through their cards, the user can click the delete button to remove the card. This will display a delete modal prompting the user to confirm or cancel. If confirmed, the card will be deleted from the database and the card 
list will render the card list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 1 24 02 PM](https://user-images.githubusercontent.com/49361894/189751891-636cb2d4-95b5-4619-9c2a-76b7168d5d05.png)
![Screen Shot 2022-09-12 at 1 24 15 PM](https://user-images.githubusercontent.com/49361894/189751895-afc80e7c-9c33-4e4f-9626-54a9bfbe1388.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle a delete request for a specified cardID
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Edit Cards Component to include a delete button for deleting the current card.
- [x] Implement a Delete Card Modal to confirm deletion request.
- [x] Handle the deletion of the card in the client-side cards array.
- [x] Update URL to properly render the next card in cards array. If we are at the end of the cards array, render the previous card.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
