### ISSUE TITLE
Feature: User can sign out of account

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/deck-study#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of the Deck Study account. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the SIgn Out Button on the navigation menu. This will render the SIgn Out modal, prompting the user to confirm their sign out request. If confirmed, the user will be signed out and redirected to the home landing page of the application. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 1 26 30 PM](https://user-images.githubusercontent.com/49361894/189752323-c2663601-dc77-452b-b131-64c577143844.png)
![Screen Shot 2022-09-12 at 1 27 01 PM](https://user-images.githubusercontent.com/49361894/189752325-f160c17f-f43e-40b1-b9cd-5440dac8768a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a handleSignOut method on app.jsx that will remove token from local storage.
- [x] In handleSignOut method, update state of user and token to null after the token is removed.
- [x] Pass the handleSignOut method to the navbar component as a prop and call this method as a callback to an onClick event on the Sign Out Button. 
- [x] Test and ensure that the token is deleted when Sign Out is clicked. App should reset to default welcome screen.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
